login: &login
  adapter: postgresql
  host: localhost
  username: Santiago
  password: tr3sco
  encoding: utf8

development:
  database: twitter
  <<: *login

test:
  database: twitter
  <<: *login

production:
  database: twitter
  <<: *login
